# Generated by Django 2.0.9 on 2018-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerritos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatadospost',
            name='fotografia',
            field=models.ImageField(upload_to='misPerritos\\Fotos'),
        ),
    ]
