# Generated by Django 2.0.9 on 2018-11-17 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('codigoAdoptante', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=20)),
                ('apPaterno', models.CharField(max_length=20)),
                ('apMaterno', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.IntegerField(null=True)),
                ('tipoVivienda', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigoCiudad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreCiudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas')),
                ('adoptante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sistema.Adoptante')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('codigoMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=30)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codigoRegion', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreRegion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sistema.Region'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sistema.Ciudad'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
